[appearance]
border_focused = "#{{colors.primary.default.hex_stripped}}FF"
border_unfocused = "#{{colors.surface_variant.default.hex_stripped}}FF"
scratchpad_border_focused = "#{{colors.tertiary.default.hex_stripped}}FF"
scratchpad_border_unfocused = "#{{colors.tertiary_container.default.hex_stripped}}FF"
outer_border_color = "#{{colors.terminal_background.default.hex_stripped}}FF"
insert_hint_color = "#{{colors.tertiary.default.hex_stripped}}80"
backdrop_color = "#{{colors.surface_variant.default.hex_stripped}}FF"

[overview]
background_tint = "#{{colors.surface.default.hex_stripped}}30"
