blank_issues_enabled: false
contact_links:
  - name: Noctalia Fluxer
    url: https://fluxer.gg/Noctalia
    about: Join the community for support, discussions, and quick help.
  - name: Noctalia Docs
    url: https://docs.noctalia.dev
    about: Browse the documentation, guides, and frequently asked questions.