[config]

[catalog.alacritty]
name = "Alacritty"
category = "terminal"

[catalog.btop]
name = "Btop"
category = "misc"

[catalog.foot]
name = "Foot"
category = "terminal"

[catalog.ghostty]
name = "Ghostty"
category = "terminal"

[catalog.gtk3]
name = "GTK 3"
category = "system"

[catalog.gtk4]
name = "GTK 4"
category = "system"

[catalog.helix]
name = "Helix"
category = "editor"

[catalog.kcolorscheme]
name = "KColorScheme"
category = "system"

[catalog.kitty]
name = "Kitty"
category = "terminal"

[catalog.labwc]
name = "Labwc"
category = "compositor"

[catalog.niri]
name = "Niri"
category = "compositor"

[catalog.hyprland]
name = "Hyprland"
category = "compositor"

[catalog.mango]
name = "Mango"
category = "compositor"

[catalog.qtct]
name = "Qt"
category = "system"

[catalog.scroll]
name = "Scroll"
category = "compositor"

[catalog.sway]
name = "Sway"
category = "compositor"

[catalog.starship]
name = "Starship"
category = "terminal"

[catalog.wezterm]
name = "Wezterm"
category = "terminal"

[catalog.yazi]
name = "Yazi"
category = "misc"

[templates.alacritty]
input_path = "./alacritty/alacritty.toml"
output_path = "~/.config/alacritty/themes/noctalia.toml"
post_hook = "bash '{{ config_dir }}/alacritty/apply.sh'"

[templates.btop]
input_path = "./btop/btop.theme"
output_path = "~/.config/btop/themes/noctalia.theme"
post_hook = "bash '{{ config_dir }}/btop/apply.sh'"

[templates.foot]
input_path = "./foot/foot"
output_path = "~/.config/foot/themes/noctalia"
post_hook = "bash '{{ config_dir }}/foot/apply.sh'"

[templates.ghostty]
input_path = "./ghostty/ghostty"
output_path = "~/.config/ghostty/themes/noctalia"
post_hook = "bash '{{ config_dir }}/ghostty/apply.sh'"

[templates.gtk3]
input_path = "./gtk/gtk3.css"
output_path = "~/.config/gtk-3.0/noctalia.css"
post_hook = "bash '{{ config_dir }}/gtk/apply.sh' {{ mode }}"

[templates.gtk4]
input_path = "./gtk/gtk4.css"
output_path = "~/.config/gtk-4.0/noctalia.css"
post_hook = "bash '{{ config_dir }}/gtk/apply.sh' {{ mode }}"

[templates.helix]
input_path = "./helix/helix.toml"
output_path = "~/.config/helix/themes/noctalia.toml"

[templates.kcolorscheme]
input_path = "./kde/kcolorscheme.colors"
output_path = "~/.local/share/color-schemes/noctalia.colors"
post_hook = "python3 '{{ config_dir }}/kde/apply.py' noctalia"

[templates.kitty]
input_path = "./kitty/kitty.conf"
output_path = "~/.config/kitty/themes/noctalia.conf"
post_hook = "bash '{{ config_dir }}/kitty/apply.sh'"

[templates.labwc]
input_path = "./labwc/labwc.conf"
output_path = "~/.config/labwc/noctalia.conf"
post_hook = "bash '{{ config_dir }}/labwc/apply.sh'"

[templates.niri]
input_path = "./niri/niri.kdl"
output_path = "~/.config/niri/noctalia.kdl"
post_hook = "bash '{{ config_dir }}/niri/apply.sh'"

[templates.hyprland]
input_path = "./hyprland/hyprland.conf"
output_path = "~/.config/hypr/noctalia.conf"
post_hook = "bash '{{ config_dir }}/hyprland/apply.sh'"

[templates.mango]
input_path = "./mango/mango.conf"
output_path = "~/.config/mango/noctalia.conf"
post_hook = "bash '{{ config_dir }}/mango/apply.sh'"

[templates.qtct]
input_path = "./qt/qtct.conf"
output_path = ["~/.config/qt5ct/colors/noctalia.conf", "~/.config/qt6ct/colors/noctalia.conf"]

[templates.scroll]
input_path = "./scroll/scroll"
output_path = "~/.config/scroll/noctalia"
post_hook = "bash '{{ config_dir }}/scroll/apply.sh'"

[templates.sway]
input_path = "./sway/sway"
output_path = "~/.config/sway/noctalia"
post_hook = "bash '{{ config_dir }}/sway/apply.sh'"

[templates.starship]
input_path = "./starship/starship.toml"
output_path = "~/.cache/noctalia/starship-palette.toml"
post_hook = "bash '{{ config_dir }}/starship/apply.sh'"

[templates.wezterm]
input_path = "./wezterm/wezterm.toml"
output_path = "~/.config/wezterm/colors/Noctalia.toml"
post_hook = "bash '{{ config_dir }}/wezterm/apply.sh'"

[templates.yazi]
input_path = "./yazi/yazi.toml"
output_path = "~/.config/yazi/flavors/noctalia.yazi/flavor.toml"
post_hook = "bash '{{ config_dir }}/yazi/apply.sh'"
